apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-engine.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ai-engine.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
